# Generated by Django 5.1.6 on 2025-04-09 08:17

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Your full name', max_length=200)),
                ('title', models.CharField(help_text='Your professional title', max_length=200)),
                ('bio', models.TextField(help_text='Tell us about yourself')),
                ('short_bio', models.CharField(blank=True, help_text='Short version for previews', max_length=200)),
                ('image', models.ImageField(help_text='Profile picture (recommended size: 800x800px)', upload_to='about/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'About',
                'verbose_name_plural': 'About',
            },
        ),
        migrations.CreateModel(
            name='BlogPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('slug', models.SlugField(blank=True, max_length=255, unique=True)),
                ('content', models.TextField()),
                ('excerpt', models.CharField(blank=True, max_length=300)),
                ('image', models.ImageField(help_text='Featured image for the blog post', upload_to='blog/%Y/%m/%d/')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published')], default='draft', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-published_at'],
                'get_latest_by': 'published_at',
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('slug', models.SlugField(blank=True, max_length=255, unique=True)),
                ('description', models.TextField()),
                ('image', models.ImageField(blank=True, default='defaults/project.png', help_text='Upload a project image', upload_to='projects/%Y/%m/%d/')),
                ('is_featured', models.BooleanField(default=False)),
                ('github_url', models.URLField(blank=True, help_text='URL to GitHub repository', validators=[django.core.validators.URLValidator(schemes=['http', 'https', 'git'])])),
                ('live_url', models.URLField(blank=True, help_text='URL to live project', validators=[django.core.validators.URLValidator(schemes=['http', 'https'])])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Project',
                'verbose_name_plural': 'Projects',
                'ordering': ['-is_featured', '-created_at'],
                'indexes': [models.Index(fields=['slug'], name='myapp_proje_slug_044a2e_idx'), models.Index(fields=['is_featured'], name='myapp_proje_is_feat_a35115_idx')],
            },
        ),
    ]
